version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: tsm-kartel-api:latest
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=${API_PORT:-8000}
      - DEBUG=${DEBUG:-false}
      - TRUST_PROXY=${TRUST_PROXY:-false}
      - WORKERS=${WORKERS:-1}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:${API_PORT:-8000}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
